<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!--
    1、async修饰的函数
        函数的返回值为Promise对象
        Promise实例的结果由async函数执行的返回值决定

    2、await表达式
        await右侧的表达式一般为Promise实例对象，但也可以是其他的值
        如果表达式是Promise实例对象，await后的返回值是Promise成功的值
        如果表达式是其他值，直接将此值作为await的返回值

     3、注意：
        await必须写在async函数中，但async函数中可以没有await
        如果await的Promise实例失败了，就会抛出异常，需要通过try...catch来捕获处理
-->

<script>
    function sendAjax(url, data, index) {
        return new Promise((resolve, reject) => {
            //实例化xhr
            const xhr = new XMLHttpRequest()
            //监听绑定
            xhr.onreadystatechange = () => {
                if (xhr.readyState === 4) {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        resolve(xhr.response)
                    } else {
                        reject(`第${index}请求出了点问题`)
                    }
                }
            }

            //整理参数
            let str = ''
            for (let key in data) {
                str += `${key}=${data[key]}`
            }
            str = str.slice(0, -1)
            xhr.open('GET', url + '?' + str)
            xhr.responseType = 'json'
            xhr.send()
        })
    }

    let params = {page: 1, count: 2, type: 'video'}
    /*    //发送第1次请求
        sendAjax('http://poetry.apiopen.top/sentences', params, 1)
            .then(
                value => {
                    console.log('第一次请求成功了', value);
                    //发送第2次请求
                    return sendAjax('http://poetry.apiopen.top/sentences2', params, 2)
                },
                /!*reason => {
                    console.log('第一次请求失败了', reason);
                    return new Promise(() => {
                    })
                }*!/
            )
            .then(
                value => {
                    console.log('第二次请求成功了', value);
                    //发送第3次请求
                    return sendAjax('http://poetry.apiopen.top/sentences', params, 3)
                },
                /!*reason => {
                    console.log('第二次请求失败了', reason);
                    return new Promise(() => {
                    })
                }*!/
            )
            .then(
                value => {
                    console.log('第三次请求成功了', value);
                },
                /!*reason => {
                    console.log('第三次请求失败了', reason);
                    return new Promise(() => {
                    })
                }*!/
            )
            .catch(reason => {
                console.log(reason);
            })*/

    !(async () => {
        try {
            const p1 = await sendAjax('http://poetry.apiopen.top/sentences', params, 1)
            console.log(p1);
            const p2 = await sendAjax('http://poetry.apiopen.top/sentences', params, 1)
            console.log(p2);
            const p3 = await sendAjax('http://poetry.apiopen.top/sentences', params, 1)
            console.log(p3);
        } catch (err) {
            console.log(err);
        }
    })()

</script>
</body>
</html>